server:
  port: 8080
spring:
  application:
    name: money-transfer
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
        logger-level: full

logging:
  level:
    com.mashreq.money.transfer: DEBUG

app:
  services:
    accountService:
      url: ${ACCOUNT_SERVICE_HOST:https://k0wo9.wiremockapi.cloud}
    coreMoneyTransferService:
      url: ${MONEY_TRANSFER_SERVICE_HOST:https://k0wo9.wiremockapi.cloud}

springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.path: /swagger-ui.html
